### ISSUE TITLE
I have an issue with this

### ISSUE THREAD

**Issue by kevinroberts** [kellerk5/top-secret-security-clearance-required#1]
i dont feel safe with this repo being empty

**Comment by kevinroberts** [comment]
i see you added some CSS but im still concerned

**Comment by kevinroberts** [comment]
Now there is some HTML too, omg

**Comment by kellerk5** [comment]
Hello, please beware of RADIOACTIVE css and markup. It may explode at any moment.

**Comment by kevinroberts** [comment]
unacceptable, i will only settle this if you add some Plutonium grade JS.

**Comment by kevinroberts** [comment]
FINE I'm going to create my own top secret repo with black jack and nachos!
